// frontend/src/components/NotificationToast.jsx
import React from 'react';
import { useNotificationStore } from '../store/notificationStore';
import { AnimatePresence, motion } from 'framer-motion';
import { X, CheckCircle2, AlertCircle, Info, AlertTriangle } from 'lucide-react';

const NotificationToast = () => {
  const { isVisible, message, type, hideNotification } = useNotificationStore();

  const icons = {
    success: <CheckCircle2 className="w-5 h-5 text-emerald-500" />,
    error: <AlertCircle className="w-5 h-5 text-rose-500" />,
    warning: <AlertTriangle className="w-5 h-5 text-amber-500" />,
    info: <Info className="w-5 h-5 text-brand-500" />
  };

  const bgColors = {
    success: 'bg-emerald-50 border-emerald-100',
    error: 'bg-rose-50 border-rose-100',
    warning: 'bg-amber-50 border-amber-100',
    info: 'bg-brand-50 border-brand-100'
  };

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0, y: 50, x: '-50%' }}
          animate={{ opacity: 1, y: 0, x: '-50%' }}
          exit={{ opacity: 0, y: 20, x: '-50%' }}
          className={`fixed bottom-10 left-1/2 z-[100] min-w-[320px] p-4 rounded-2xl border shadow-2xl flex items-center gap-4 ${bgColors[type]}`}
        >
          {icons[type]}
          <div className="flex-1">
            <p className="text-sm font-bold text-surface-900">{message}</p>
          </div>
          <button 
            onClick={hideNotification}
            className="p-1 hover:bg-white rounded-lg transition-colors text-surface-400 hover:text-surface-900"
          >
            <X className="w-4 h-4" />
          </button>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default NotificationToast;

// frontend/src/components/NotificationToast.vue
<script setup>
import { useNotificationStore } from '../stores/notifications'
import { computed } from 'vue'

const notificationStore = useNotificationStore()

const notificationClass = computed(() => {
  switch (notificationStore.type) {
    case 'success':
      return 'bg-green-500'
    case 'error':
      return 'bg-red-500'
    case 'warning':
      return 'bg-yellow-500'
    case 'info':
      return 'bg-blue-500'
    default:
      return 'bg-gray-500'
  }
})
</script>

<template>
  <Transition
    enter-active-class="transition ease-out duration-300"
    enter-from-class="transform opacity-0 scale-95"
    enter-to-class="transform opacity-100 scale-100"
    leave-active-class="transition ease-in duration-200"
    leave-from-class="transform opacity-100 scale-100"
    leave-to-class="transform opacity-0 scale-95"
  >
    <div
      v-if="notificationStore.isVisible"
      :class="notificationClass"
      class="fixed bottom-5 right-5 p-4 rounded-md shadow-lg text-white max-w-sm z-50"
    >
      <div class="flex justify-between items-center">
        <span>{{ notificationStore.message }}</span>
        <button @click="notificationStore.hideNotification()" class="ml-4 text-white hover:text-gray-100 focus:outline-none">
          &times;
        </button>
      </div>
    </div>
  </Transition>
</template>
