// frontend/src/components/PropertyCard.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { BaseCard } from './BaseCard';
import { MapPin, Users, Bed, Bath, ArrowRight } from 'lucide-react';

const PropertyCard = ({ property }) => {
  return (
    <BaseCard padding="none" hover className="group overflow-hidden flex flex-col h-full">
      <div className="relative h-64 overflow-hidden">
        <img 
          src={property.images?.[0]?.image || 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800'} 
          alt={property.title}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
        />
        <div className="absolute top-4 right-4 px-4 py-2 bg-white/90 backdrop-blur-md rounded-xl text-sm font-black text-surface-900 shadow-sm">
          ${property.base_price}<span className="text-[10px] text-surface-500 font-bold">/night</span>
        </div>
      </div>

      <div className="p-6 flex-1 flex flex-col">
        <div className="flex items-center gap-1.5 text-brand-600 text-[10px] font-black uppercase tracking-widest mb-2">
          <MapPin className="w-3 h-3" />
          {property.property_title}
        </div>
        
        <h3 className="text-xl font-bold text-surface-900 mb-2 line-clamp-1 group-hover:text-brand-600 transition-colors">
          {property.title}
        </h3>
        
        <p className="text-sm text-surface-500 font-medium mb-6 line-clamp-2">
          {property.description}
        </p>

        <div className="mt-auto flex items-center justify-between pt-6 border-t border-surface-50">
          <div className="flex items-center gap-4 text-surface-400">
            <div className="flex items-center gap-1.5">
              <Bed className="w-4 h-4" />
              <span className="text-xs font-bold text-surface-700">{property.features?.bedrooms || 1}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Users className="w-4 h-4" />
              <span className="text-xs font-bold text-surface-700">{property.features?.guests || 2}</span>
            </div>
          </div>
          
          <Link 
            to={`/unit/${property.id}`}
            className="flex items-center gap-2 text-sm font-black text-surface-900 group-hover:text-brand-600 transition-all"
          >
            View Details
            <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </Link>
        </div>
      </div>
    </BaseCard>
  );
};

export default PropertyCard;

// frontend/src/components/PropertyCard.vue
<script setup>
defineProps({
  property: {
    type: Object,
    required: true
  }
})
</script>

<template>
  <div class="group bg-white rounded-[2rem] border border-slate-100 overflow-hidden hover:shadow-xl hover:shadow-indigo-500/10 transition-all duration-300">
    <!-- Image Placeholder with Gradient -->
    <div class="relative h-48 bg-slate-100 overflow-hidden">
      <div class="absolute inset-0 bg-gradient-to-br from-indigo-500/20 to-violet-500/20 group-hover:scale-110 transition-transform duration-500"></div>
      <div class="absolute inset-0 flex items-center justify-center text-slate-300">
        <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/></svg>
      </div>
      <div class="absolute top-4 right-4 px-3 py-1.5 bg-white/90 backdrop-blur shadow-sm rounded-xl text-xs font-bold text-slate-900">
        ${{ property.base_price }}<span class="text-slate-500 font-medium">/night</span>
      </div>
    </div>

    <div class="p-6">
      <div class="flex flex-col mb-2">
        <span class="text-[10px] font-black text-indigo-500 uppercase tracking-widest">{{ property.property_title }}</span>
        <h3 class="text-lg font-bold text-slate-900 leading-tight group-hover:text-indigo-600 transition-colors">
          {{ property.title }} ({{ property.unit_number }})
        </h3>
      </div>
      
      <p class="text-sm text-slate-500 line-clamp-2 mb-4 h-10">
        {{ property.description }}
      </p>

      <router-link 
        :to="{ name: 'unit-detail', params: { id: property.id }}" 
        class="w-full inline-flex justify-center items-center px-6 py-3 bg-slate-900 text-white text-sm font-bold rounded-xl hover:bg-indigo-600 transition-all"
      >
        View Suite
        <svg class="ml-2 w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </router-link>
    </div>
  </div>
</template>
