// frontend/src/layouts/DefaultLayout.jsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate, Outlet } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
import { useNotificationStore } from '../store/notificationStore';
import { 
  LayoutDashboard, Search, Calendar, LogOut, Menu, X, Bell, Home, ShieldCheck 
} from 'lucide-react';
import { BaseButton } from '../components/BaseButton';
import { AnimatePresence, motion } from 'framer-motion';
import { twMerge } from 'tailwind-merge';
import Omnisearch from '../components/Omnisearch';

const DefaultLayout = () => {
  const { user, isAuthenticated, logout } = useAuthStore();
  const { connect, disconnect } = useNotificationStore();
  const [isSidebarOpen, setSidebarOpen] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    if (isAuthenticated) {
      connect();
    }
    return () => disconnect();
  }, [isAuthenticated]);

  const navigation = [
    { name: 'Home', href: '/', icon: Home },
    { name: 'Discover', href: '/discover', icon: Search },
    { name: 'My Bookings', href: '/my-bookings', icon: Calendar, role: 'tenant' },
    { name: 'Landlord Dashboard', href: '/landlord-dashboard', icon: LayoutDashboard, role: 'landlord' },
  ].filter(item => !item.role || (user?.role === item.role));

  const isActive = (path) => location.pathname === path;

  return (
    <div className="min-h-screen bg-surface-50 flex">
      {/* Sidebar */}
      <aside className="hidden lg:flex flex-col w-72 bg-white border-r border-surface-200 sticky top-0 h-screen z-50">
        <div className="p-8">
          <Link to="/" className="flex items-center gap-3">
            <div className="w-10 h-10 bg-brand-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-brand-500/30">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <span className="text-2xl font-black text-surface-900 tracking-tight">PropManage</span>
          </Link>
        </div>

        <nav className="flex-1 px-4 space-y-2">
          {navigation.map((item) => (
            <Link
              key={item.name}
              to={item.href}
              className={twMerge(
                'group flex items-center px-4 py-3.5 text-sm font-semibold rounded-2xl transition-all duration-200',
                isActive(item.href)
                  ? 'bg-brand-50 text-brand-700 shadow-sm shadow-brand-100/50'
                  : 'text-surface-500 hover:bg-surface-50 hover:text-surface-900'
              )}
            >
              <item.icon className="mr-3 w-5 h-5 transition-colors" />
              {item.name}
            </Link>
          ))}
        </nav>

        <div className="p-4 mt-auto">
          {isAuthenticated ? (
            <div className="bg-surface-50 rounded-3xl p-4 border border-surface-100">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-brand-100 flex items-center justify-center text-brand-700 font-bold">
                  {user?.first_name?.[0]}{user?.last_name?.[0]}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-bold text-surface-900 truncate">{user?.first_name} {user?.last_name}</p>
                  <p className="text-xs text-surface-500 capitalize">{user?.role}</p>
                </div>
              </div>
              <BaseButton 
                variant="ghost" 
                size="sm" 
                className="w-full justify-start text-red-600 hover:bg-red-50 hover:text-red-700"
                onClick={() => {
                  logout();
                  navigate('/login');
                }}
              >
                <LogOut className="w-4 h-4 mr-2" />
                Logout
              </BaseButton>
            </div>
          ) : (
            <div className="space-y-2">
              <Link to="/login"><BaseButton variant="secondary" className="w-full">Sign In</BaseButton></Link>
              <Link to="/register"><BaseButton className="w-full">Join Now</BaseButton></Link>
            </div>
          )}
        </div>
      </aside>

      <div className="flex-1 flex flex-col min-w-0">
        <header className="flex items-center justify-between px-4 lg:px-10 py-6 sticky top-0 bg-surface-50/80 backdrop-blur-sm z-30">
          <div className="flex items-center gap-4">
            <button onClick={() => setSidebarOpen(true)} className="lg:hidden p-2 text-surface-500 hover:bg-white rounded-xl">
              <Menu className="w-6 h-6" />
            </button>
            <h2 className="text-lg font-bold text-surface-900 capitalize hidden sm:block">
              {location.pathname.split('/').pop()?.replace('-', ' ') || 'Overview'}
            </h2>
          </div>
          <div className="flex items-center gap-4">
             <Omnisearch />
             <div className="h-8 w-[1px] bg-surface-200 mx-2 hidden lg:block"></div>
             <button className="p-2.5 text-surface-400 hover:text-brand-600 hover:bg-white rounded-xl transition-all border border-transparent hover:border-surface-200 relative">
               <Bell className="w-5 h-5" />
             </button>
          </div>
        </header>

        <main className="flex-1 px-4 lg:px-10 pb-10">
          <Outlet />
        </main>
      </div>

      {/* Mobile Sidebar can be added later if needed */}
    </div>
  );
};

export default DefaultLayout;

// frontend/src/layouts/DefaultLayout.vue
<script setup>
import { ref } from 'vue'
import { useAuthStore } from '../stores/auth'
import { useRouter, useRoute } from 'vue-router'

const auth = useAuthStore()
const router = useRouter()
const route = useRoute()
const isSidebarOpen = ref(false)

function handleLogout() {
  auth.logout()
  router.push('/login')
}

const navigation = [
  { name: 'Discover', href: '/properties', icon: 'search' },
  { name: 'My Bookings', href: '/my-bookings', icon: 'calendar', role: 'tenant' },
  { name: 'Landlord Dashboard', href: '/landlord-dashboard', icon: 'layout', role: 'landlord' },
]

function isActive(path) {
  return route.path === path
}
</script>

<template>
  <div class="min-h-screen bg-slate-50 flex flex-col">
    <!-- Top Navigation -->
    <header class="bg-white border-b border-slate-200 sticky top-0 z-40">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex justify-between items-center">
        <div class="flex items-center gap-4">
          <button @click="isSidebarOpen = !isSidebarOpen" class="lg:hidden p-2 text-slate-500 hover:bg-slate-100 rounded-lg">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>
          </button>
          <router-link to="/" class="flex items-center gap-2">
            <div class="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white font-bold">P</div>
            <span class="text-xl font-bold text-slate-900 tracking-tight">PropManage</span>
          </router-link>
        </div>

        <div class="flex items-center gap-4">
          <template v-if="auth.isAuthenticated">
            <div class="hidden sm:flex flex-col items-end mr-2">
              <span class="text-sm font-semibold text-slate-900">{{ auth.user?.first_name }} {{ auth.user?.last_name }}</span>
              <span class="text-xs text-slate-500 capitalize">{{ auth.user?.role }}</span>
            </div>
            <button @click="handleLogout" class="px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100 rounded-lg transition-colors">
              Logout
            </button>
          </template>
          <template v-else>
            <router-link to="/login" class="px-4 py-2 text-sm font-medium text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors">
              Sign In
            </router-link>
            <router-link to="/register" class="px-4 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition-shadow shadow-sm">
              Get Started
            </router-link>
          </template>
        </div>
      </div>
    </header>

    <div class="flex flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-8 gap-8">
      <!-- Sidebar Navigation (Desktop) -->
      <aside class="hidden lg:block w-64 flex-shrink-0">
        <nav class="space-y-1 sticky top-24">
          <router-link 
            v-for="item in navigation.filter(n => !n.role || (auth.isAuthenticated && auth.user?.role === n.role))" 
            :key="item.name"
            :to="item.href"
            :class="[
              isActive(item.href) 
                ? 'bg-indigo-50 text-indigo-700' 
                : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900',
              'group flex items-center px-3 py-2.5 text-sm font-medium rounded-xl transition-all'
            ]"
          >
            <span class="mr-3">
               <!-- Simple Icon Placeholders -->
               <svg v-if="item.icon === 'search'" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
               <svg v-if="item.icon === 'calendar'" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line x1="16" x2="16" y1="2" y2="6"/><line x1="8" x2="8" y1="2" y2="6"/><line x1="3" x2="21" y1="10" y2="10"/></svg>
               <svg v-if="item.icon === 'layout'" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/></svg>
            </span>
            {{ item.name }}
          </router-link>
        </nav>
      </aside>

      <!-- Main Content -->
      <main class="flex-1 min-w-0">
        <router-view v-slot="{ Component }">
          <transition 
            enter-active-class="transition ease-out duration-200" 
            enter-from-class="opacity-0 translate-y-4" 
            enter-to-class="opacity-100 translate-y-0"
            leave-active-class="transition ease-in duration-150"
            leave-from-class="opacity-100 translate-y-0"
            leave-to-class="opacity-0 translate-y-4"
            mode="out-in"
          >
            <component :is="Component" />
          </transition>
        </router-view>
      </main>
    </div>

    <!-- Mobile Sidebar Overlay -->
    <div v-if="isSidebarOpen" @click="isSidebarOpen = false" class="fixed inset-0 bg-slate-900/50 z-50 lg:hidden"></div>
    <div 
      :class="[
        isSidebarOpen ? 'translate-x-0' : '-translate-x-full',
        'fixed inset-y-0 left-0 w-64 bg-white z-50 lg:hidden transition-transform duration-300 ease-in-out p-6'
      ]"
    >
      <div class="flex items-center justify-between mb-8">
        <span class="text-xl font-bold text-slate-900">Menu</span>
        <button @click="isSidebarOpen = false" class="p-2 text-slate-500">
           <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" x2="6" y1="6" y2="18"/><line x1="6" x2="18" y1="6" y2="18"/></svg>
        </button>
      </div>
       <nav class="space-y-2">
          <router-link 
            v-for="item in navigation.filter(n => !n.role || (auth.isAuthenticated && auth.user?.role === n.role))" 
            :key="item.name"
            :to="item.href"
            @click="isSidebarOpen = false"
            :class="[
              isActive(item.href) ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600',
              'flex items-center px-4 py-3 text-base font-medium rounded-xl'
            ]"
          >
            {{ item.name }}
          </router-link>
        </nav>
    </div>
  </div>
</template>

<style scoped>
.router-link-active {
  @apply bg-indigo-50 text-indigo-700;
}
</style>
